
services:
  backend:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${DATABASE_URL}
      - JWT__Key=${JWT__Key}
      - AllowedOrigins=http://localhost:3000;https://your-production-domain.com

  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend

