
services:
  backend:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${DATABASE_URL}
      - AllowedOrigins=http://localhost:3000;https://your-production-domain.com
    depends_on:
      - frontend

  frontend:
    build: ./client
    ports:
      - "3000:80"

